// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: articles.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (id, created_at, updated_at, user_id, category_id, title, body, image_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, user_id, category_id, title, body, image_url
`

type CreateArticleParams struct {
	UserID     uuid.UUID
	CategoryID uuid.UUID
	Title      string
	Body       json.RawMessage
	ImageUrl   sql.NullString
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Body,
		arg.ImageUrl,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
where id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
Select a.id, a.created_at, a.updated_at, a.user_id, a.category_id, a.title, a.body, a.image_url, users.username
FROM articles a
JOIN users on a.user_id = users.id
WHERE a.id = $1
`

type GetArticleRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	CategoryID uuid.UUID
	Title      string
	Body       json.RawMessage
	ImageUrl   sql.NullString
	Username   string
}

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (GetArticleRow, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.Username,
	)
	return i, err
}

const getArticles = `-- name: GetArticles :many
SELECT a.id, a.created_at, a.updated_at, a.user_id, a.category_id, a.title, a.body, a.image_url, users.username
FROM articles a
JOIN users ON a.user_id = users.id
ORDER BY a.created_at ASC
LIMIT $1 OFFSET $2
`

type GetArticlesParams struct {
	Limit  int32
	Offset int32
}

type GetArticlesRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	CategoryID uuid.UUID
	Title      string
	Body       json.RawMessage
	ImageUrl   sql.NullString
	Username   string
}

func (q *Queries) GetArticles(ctx context.Context, arg GetArticlesParams) ([]GetArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesRow
	for rows.Next() {
		var i GetArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Body,
			&i.ImageUrl,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticlesByUserId = `-- name: GetArticlesByUserId :many
SELECT a.id, a.created_at, a.updated_at, a.user_id, a.category_id, a.title, a.body, a.image_url, users.username
FROM articles a
JOIN users ON a.user_id = users.id
WHERE a.user_id = $1
ORDER BY a.created_at ASC
LIMIT $2 OFFSET $3
`

type GetArticlesByUserIdParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetArticlesByUserIdRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	CategoryID uuid.UUID
	Title      string
	Body       json.RawMessage
	ImageUrl   sql.NullString
	Username   string
}

func (q *Queries) GetArticlesByUserId(ctx context.Context, arg GetArticlesByUserIdParams) ([]GetArticlesByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArticlesByUserIdRow
	for rows.Next() {
		var i GetArticlesByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Body,
			&i.ImageUrl,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalArticlesCount = `-- name: GetTotalArticlesCount :one
SELECT COUNT(*) FROM articles
`

func (q *Queries) GetTotalArticlesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalArticlesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
